# Generated by Django 6.0.7 on 2026-07-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
