# Generated by Django 6.0.7 on 2026-08-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='admin', max_length=100),
            preserve_default=False,
        ),
    ]
