# Generated by Django 6.0.7 on 2026-08-27 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_authors(apps, schema_editor):
    Post = apps.get_model('blog', 'Post')
    User = apps.get_model('auth', 'User')

    for post in Post.objects.all():
        if post.author:
            try:
                user = User.objects.get(username=post.author)
                post.author_user = user
                post.save(update_fields=['author_user'])
            except User.DoesNotExist:
                post.author_user = None
                post.save(update_fields=['author_user'])


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_profile_last_confirmation_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts_authored_temp',
                to=settings.AUTH_USER_MODEL,
            ),
        ),

        migrations.RunPython(
            migrate_authors,
            migrations.RunPython.noop,
        ),

        migrations.RemoveField(
            model_name='post',
            name='author',
        ),

        migrations.RenameField(
            model_name='post',
            old_name='author_user',
            new_name='author',
        ),

        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts_authored',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]